version: 2
updates:
  - package-ecosystem: npm
    directory: "/tests/UI"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
    open-pull-requests-limit: 10
    target-branch: dev
    reviewers:
      - "PrestaShop/qa-automation"
    labels:
      - "dependencies"
      - "E2E Tests"
      - "TE"
