name: PHP tests
on: [push, pull_request]
jobs:
  php-linter:
    name: PHP Syntax check 7.2 => 8.4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: PHP syntax checker 7.2
        uses: prestashop/github-action-php-lint/7.2@master

      - name: PHP syntax checker 7.3
        uses: prestashop/github-action-php-lint/7.3@master

      - name: PHP syntax checker 7.4
        uses: prestashop/github-action-php-lint/7.4@master

      - name: PHP syntax checker 8.0
        uses: prestashop/github-action-php-lint/8.0@master

      - name: PHP syntax checker 8.1
        uses: prestashop/github-action-php-lint/8.1@master

      - name: PHP syntax checker 8.2
        uses: prestashop/github-action-php-lint/8.2@master

      - name: PHP syntax checker 8.3
        uses: prestashop/github-action-php-lint/8.3@master

      - name: PHP syntax checker 8.4
        uses: prestashop/github-action-php-lint/8.4@master

  # Check the PHP code follow the coding standards
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: php-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        run: composer install

      - name: Run PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no

  # Run PHPStan against the module and a PrestaShop release
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - prestashop-version: '8.0.5'
            php-version: '7.4'
          - prestashop-version: '8.1.7'
            php-version: '7.4'
          - prestashop-version: '8.2.x'
            php-version: '7.4'
          - prestashop-version: '9.0.3'
            php-version: '8.1'
          - prestashop-version: 'develop'
            php-version: '8.1'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
      
      - uses: PrestaShop/.github/.github/actions/php-ci/phpstan@master
        with:
          php-version: ${{ matrix.php-version }}
          presta-version: ${{ matrix.prestashop-version }}
          module-name: ${{ github.event.repository.name }}
          phpstan-level: '5'
          phpstan-config: 'tests/phpstan/phpstan-${{ matrix.prestashop-version }}.neon'
          phpstan-version: '^0.12'
          composer-version: '2.2.18'
